source "https://www.rubygems.org"

gem "sinatra"
gem "sinatra-minify"
gem "rake"
gem "thin"
gem "unicorn"
gem "rack-contrib"
gem "haml"
gem "sinatra-activerecord"
gem "activerecord"
gem "activeresource"
gem "mysql"
gem "google-drive"
